- name: "Install locales package"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: locales
    state: present

- name: "Set locale to Ubuntu"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present
